apiVersion: v1
kind: Service
metadata:
  name: student-backend
  labels:
    app.kubernetes.io/name: student-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: student-management
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: student-backend
  ports:
    - name: http
      port: 3000
      targetPort: http
